---
#
# Install/run logstash
#

- name: Copy logstash yum repo file
  copy:
    src=logstash.repo
    dest=/etc/yum.repos.d/logstash.repo
    owner=root
    group=root
    mode=0644

- name: Install logstash 
  yum:
    name: logstash
    lock_timeout: 180
