--- 

- name: create swapfile
  command: fallocate -l 1G /swapfile

- name: Fill swapfile by zeroes
  command: dd if=/dev/zero of=/swapfile bs=1024 count=1048576

- name: chmod swapfile
  command: chmod 600 /swapfile

- name: make swapfile as swap
  command: mkswap /swapfile

- name: turn on swapfile 
  command: swapon /swapfile
