---
#
# Install/run kibana
# 

- name: Copy kibana yum repo file
  copy:
    src=kibana.repo
    dest=/etc/yum.repos.d/kibana.repo
    owner=root
    group=root
    mode=0644
  become: true

- name: Install kibana rpms
  yum:
    name: kibana
  become: true

- name: Setup kibana service
  service: 
    name: kibana 
    state: started
    enabled: true
  become: true
