---
#
# Install/run elasticsearch
#

- name: Install JDK 8
  yum:
    name: java-1.8.0-openjdk
  become: true

- name: Copy elasticsearch yum repo file
  copy:
    src=elasticsearch.repo
    dest=/etc/yum.repos.d/elasticsearch.repo
    owner=root
    group=root
    mode=0644
  become: true

- name: add rpm key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Install elasticsearch 
  yum:
    name: elasticsearch
  become: true

- name: Setup elasticsearch service to autostart
  service: 
    name: elasticsearch
    state: started 
    enabled: true